### ISSUE TITLE
Unable to toggle Lock Interface

### ISSUE THREAD

**Issue by don1138** [DB3D/Lodify#1]
**When Lodify is active the Render Menu > Lock Interface toggle breaks**

If toggle is set to `use_lock_interface = False`, toggle to `use_lock_interface = True` works; 
but if set to `use_lock_interface = True`, then toggle to `use_lock_interface = False` does not work.

Tested in Blender 2.83.6 and 2.90.1

**Comment by kintuX** [comment]
Confirming the issue with 2.83.10 & 2.91. (OS: W10)
Activating the addon breaks the "Lock Interface" toggle by enabling and keeping it "Locked".
Disabling the addon, "Lock interface" toggle works again and can be unchecked/unlocked.
