### ISSUE TITLE
Switching to/from rendered view does not change the LOD mesh

### ISSUE THREAD

**Issue by muhuk** [DB3D/Lodify#2]
LOD mesh does not change when switching between solid/wireframe and rendered view.

- Tested with `2.3.2`
- Same issue for both Cycles & Eevee
- When rendered, correct LOD mesh is selected. (works as intended)
- I have tried both auto-generated LOD meshes and manually creating LOD setup.

**Comment by DB3D** [comment]
Thanks for the report ,
I can tell you that a new version of lodify working on geometry node will be available in a few months

>

**Comment by muhuk** [comment]
I've created [something similar with geometry nodes](https://github.com/muhuk/lod-instances). It's not very advanced but at least my viewport is responsive again. Closing this issue.
